eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url:
      # # Eureka Server注册中心的地址，用于Client与Server进行交流
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8760
spring:
  application:
    name: eureka-client-service
logging:
  level:
    org.springframework: DEBUG